"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green) 
[â”‚](bold green)  $username$hostname$sudo$time$battery $status 
[â”‚](bold green)  $directory
[â””â”€](bold green) $shell$character'''


[battery]
format = '\[[$symbol$percentage]($style)\]'
disabled = false

[status]
symbol = "ðŸ’¥"
style = 'fg:blue'
success_symbol = "ðŸš€"
format = '$symbol$common_meaning$signal_name$maybe_int($style) '
map_symbol = true
disabled = false

[sudo]
format = '\[[as $symbol]($style)\]'
disabled = false

[time]
style = 'bold #ff006e'
format = '\[[$time]($style)\]'
disabled = false


[username]
format = '\[[$user]($style)\]'
show_always = true
disabled = false

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '
disabled = false
ssh_only = false

[shell]
format = '$indicator($style)'
disabled = false

